FROM tensorflow/tensorflow

RUN pip install keras
RUN pip install h5py
RUN pip install --upgrade jupyter

RUN useradd -ms /bin/bash quickdraw-ten
WORKDIR /home/quickdraw-ten

COPY data-download.sh .
RUN chown -R quickdraw-ten .
RUN chmod +x ./data-download.sh
